export const admins = [
  {
    id: "AD001",
    superAdminId: "SA001",
    name: "Rohit Sharma",
    email: "rohit@billing.com",
    phone: "9876543210",
    image: "https://i.pravatar.cc/150?img=3",
    location: "Delhi",
    joinDate: "2025-01-10",
  },
  {
    id: "AD002",
    superAdminId: "SA001",
    name: "Amit Verma",
    email: "amit@billing.com",
    phone: "9876543211",
    image: "https://i.pravatar.cc/150?img=8",
    location: "Mumbai",
    joinDate: "2025-02-15",
  },
  {
    id: "AD003",
    superAdminId: "SA001",
    name: "Neha Singh",
    email: "neha@billing.com",
    phone: "9876543212",
    image: "https://images.pexels.com/photos/1755385/pexels-photo-1755385.jpeg",
    location: "Lucknow",
    joinDate: "2025-03-20",
  },
];

export const users = [
  {
    id: "US001",
    adminId: "AD001",
    name: "Raj Kumar",
    email: "raj@gmail.com",
    phone: "9000000001",
    image: "https://i.pravatar.cc/150?img=3",
    location: "Delhi",
    joinDate: "2025-01-10",
    createdBy: "Rahul Sharma",
  },
  {
    id: "US002",
    adminId: "AD001",
    name: "Priya Sharma",
    email: "priya@gmail.com",
    phone: "9000000002",
    image: "https://images.pexels.com/photos/1755385/pexels-photo-1755385.jpeg",
    location: "Delhi",
    joinDate: "2025-01-15",
    createdBy: "Rahul Sharma",
  },

  {
    id: "US003",
    adminId: "AD002",
    name: "Vikas Gupta",
    email: "vikas@gmail.com",
    phone: "9000000003",
    image: "https://i.pravatar.cc/150?img=13",
    location: "Mumbai",
    joinDate: "2025-02-05",
    createdBy: "Priya Singh",
  },
  {
    id: "US004",
    adminId: "AD002",
    name: "Pooja Verma",
    email: "pooja@gmail.com",
    phone: "9000000004",
    image: "https://i.pravatar.cc/150?img=14",
    location: "Mumbai",
    joinDate: "2025-02-12",
    createdBy: "Priya Singh",
  },

  {
    id: "US005",
    adminId: "AD003",
    name: "Ankit Singh",
    email: "ankit@gmail.com",
    phone: "9000000005",
    image: "https://i.pravatar.cc/150?img=15",
    location: "Lucknow",
    joinDate: "2025-03-01",
    createdBy: "Neha Singh",
  },
  {
    id: "US006",
    adminId: "AD003",
    name: "Riya Patel",
    email: "riya@gmail.com",
    phone: "9000000006",
    image: "https://i.pravatar.cc/150?img=16",
    location: "Lucknow",
    joinDate: "2025-03-08",
    createdBy: "Neha Singh",
  },
  {
    id: "US007",
    adminId: "AD003",
    name: "Mohit Yadav",
    email: "mohit@gmail.com",
    phone: "9000000007",
    image: "https://i.pravatar.cc/150?img=17",
    location: "Kanpur",
    joinDate: "2025-03-20",
    createdBy: "Neha Singh",
  },
];

{
  /*   ---------------Login Data -------------------*/
}
export const allUsers = [
  {
    id: "SA001",
    name: "Manish Kumar",
    email: "super@gmail.com",
    password: "123456",
    phone: 8536896543,
    role: "super-admin",
  },
  {
    id: "AD001",
    name: "Rahul Sharma",
    email: "admin@gmail.com",
    password: "123456",
    phone: 3234325675,
    role: "admin",
  },
  {
    id: "US001",
    name: "Raj Kumar",
    email: "user@gmail.com",
    password: "123456",
    phone: 3238769675,
    role: "user",
  },
];

// ----------------Super-Admin------Vendors------------------------

export const vendors = [
  {
    id: 1,
    name: "Rahul Sharma",
    image: "https://i.pravatar.cc/150?img=1",
    company: "ABC Pvt Ltd",
    email: "rahul@gmail.com",
    phone: "9876543210",
    status: "Active",
    joinDate: "2026-06-17",
  },
  {
    id: 2,
    name: "Amit Kumar",
    image: "https://i.pravatar.cc/150?img=2",
    company: "XYZ Traders",
    email: "amit@gmail.com",
    phone: "9876543211",
    status: "Active",
    joinDate: "2026-06-15",
  },
  {
    id: 3,
    name: "Vikas Singh",
    image: "https://i.pravatar.cc/150?img=3",
    company: "Singh Enterprises",
    email: "vikas@gmail.com",
    phone: "9876543212",
    status: "Inactive",
    joinDate: "2026-06-10",
  },
];

//----------------------------------- Category----------------------------

export const categories = [
  {
    id: 1,
    name: "Electronics",
    image: "https://picsum.photos/200?random=1",
    totalProducts: 3,
    status: "Active",
  },
  {
    id: 2,
    name: "Grocery",
    image: "https://picsum.photos/200?random=2",
    totalProducts: 3,
    status: "Active",
  },
  {
    id: 3,
    name: "Fashion",
    image: "https://picsum.photos/200?random=3",
    totalProducts: 3,
    status: "Inactive",
  },
  {
    id: 4,
    name: "Stationery",
    image: "https://picsum.photos/200?random=4",
    totalProducts: 3,
    status: "Active",
  },
  {
    id: 5,
    name: "Beverages",
    image: "https://picsum.photos/200?random=5",
    totalProducts: 3,
    status: "Inactive",
  },
];

//-----------------------------------Producty----------------------------

export const products = [
  // Electronics
  {
    id: 1,
    categoryId: 1,
    name: "Laptop",
    image: "https://picsum.photos/200?random=11",
    sku: "ELE-001",
    price: 45000,
    stock: 10,
    status: "Active",
  },
  {
    id: 2,
    categoryId: 1,
    name: "Wireless Mouse",
    image: "https://picsum.photos/200?random=12",
    sku: "ELE-002",
    price: 800,
    stock: 50,
    status: "Active",
  },
  {
    id: 3,
    categoryId: 1,
    name: "Keyboard",
    image: "https://picsum.photos/200?random=13",
    sku: "ELE-003",
    price: 1200,
    stock: 30,
    status: "Inactive",
  },

  // Grocery
  {
    id: 4,
    categoryId: 2,
    name: "Rice 5kg",
    image: "https://picsum.photos/200?random=14",
    sku: "GRO-001",
    price: 350,
    stock: 100,
    status: "Active",
  },
  {
    id: 5,
    categoryId: 2,
    name: "Sugar 1kg",
    image: "https://picsum.photos/200?random=15",
    sku: "GRO-002",
    price: 50,
    stock: 80,
    status: "Active",
  },
  {
    id: 6,
    categoryId: 2,
    name: "Wheat Flour 5kg",
    image: "https://picsum.photos/200?random=16",
    sku: "GRO-003",
    price: 250,
    stock: 60,
    status: "Inactive",
  },

  // Fashion
  {
    id: 7,
    categoryId: 3,
    name: "T-Shirt",
    image: "https://picsum.photos/200?random=17",
    sku: "FAS-001",
    price: 499,
    stock: 40,
    status: "Active",
  },
  {
    id: 8,
    categoryId: 3,
    name: "Jeans",
    image: "https://picsum.photos/200?random=18",
    sku: "FAS-002",
    price: 999,
    stock: 25,
    status: "Active",
  },
  {
    id: 9,
    categoryId: 3,
    name: "Shoes",
    image: "https://picsum.photos/200?random=19",
    sku: "FAS-003",
    price: 1499,
    stock: 20,
    status: "Inactive",
  },

  // Stationery
  {
    id: 10,
    categoryId: 4,
    name: "Notebook",
    image: "https://picsum.photos/200?random=20",
    sku: "STA-001",
    price: 60,
    stock: 200,
    status: "Active",
  },
  {
    id: 11,
    categoryId: 4,
    name: "Pen",
    image: "https://picsum.photos/200?random=21",
    sku: "STA-002",
    price: 10,
    stock: 500,
    status: "Active",
  },
  {
    id: 12,
    categoryId: 4,
    name: "Marker",
    image: "https://picsum.photos/200?random=22",
    sku: "STA-003",
    price: 40,
    stock: 100,
    status: "Inactive",
  },

  // Beverages
  {
    id: 13,
    categoryId: 5,
    name: "Coca Cola 500ml",
    image: "https://picsum.photos/200?random=23",
    sku: "BEV-001",
    price: 40,
    stock: 120,
    status: "Active",
  },
  {
    id: 14,
    categoryId: 5,
    name: "Orange Juice",
    image: "https://picsum.photos/200?random=24",
    sku: "BEV-002",
    price: 90,
    stock: 70,
    status: "Active",
  },
  {
    id: 15,
    categoryId: 5,
    name: "Mineral Water",
    image: "https://picsum.photos/200?random=25",
    sku: "BEV-003",
    price: 20,
    stock: 300,
    status: "Inactive",
  },
  {
    id: 16,
    categoryId: 5,
    name: "Mineral Water",
    image: "https://picsum.photos/200?random=25",
    sku: "BEV-003",
    price: 20,
    stock: 300,
    status: "Inactive",
  },
  {
    id: 17,
    categoryId: 5,
    name: "Mineral Water",
    image: "https://picsum.photos/200?random=25",
    sku: "BEV-003",
    price: 20,
    stock: 300,
    status: "Inactive",
  },
  {
    id: 18,
    categoryId: 5,
    name: "Mineral Water",
    image: "https://picsum.photos/200?random=25",
    sku: "BEV-003",
    price: 20,
    stock: 300,
    status: "Inactive",
  },
  {
    id: 19,
    categoryId: 5,
    name: "Mineral Water",
    image: "https://picsum.photos/200?random=25",
    sku: "BEV-003",
    price: 20,
    stock: 300,
    status: "Inactive",
  },
  {
    id: 20,
    categoryId: 5,
    name: "Mineral Water",
    image: "https://picsum.photos/200?random=25",
    sku: "BEV-003",
    price: 20,
    stock: 300,
    status: "Inactive",
  },
  {
    id: 21,
    categoryId: 5,
    name: "Mineral Water",
    image: "https://picsum.photos/200?random=25",
    sku: "BEV-003",
    price: 20,
    stock: 300,
    status: "Inactive",
  },
  {
    id: 22,
    categoryId: 5,
    name: "Mineral Water",
    image: "https://picsum.photos/200?random=25",
    sku: "BEV-003",
    price: 20,
    stock: 300,
    status: "Inactive",
  },
  {
    id: 23,
    categoryId: 5,
    name: "Mineral Water",
    image: "https://picsum.photos/200?random=25",
    sku: "BEV-003",
    price: 20,
    stock: 300,
    status: "Inactive",
  },
  {
    id: 24,
    categoryId: 5,
    name: "Mineral Water",
    image: "https://picsum.photos/200?random=25",
    sku: "BEV-003",
    price: 20,
    stock: 300,
    status: "Inactive",
  },
  {
    id: 25,
    categoryId: 5,
    name: "Mineral Water",
    image: "https://picsum.photos/200?random=25",
    sku: "BEV-003",
    price: 20,
    stock: 300,
    status: "Inactive",
  },
];

export const stats = [
  { title: "Revenue", value: "$48,295" },
  { title: "Users", value: "2,401" },
  { title: "Conversion", value: "18.6%" },
  { title: "Sessions", value: "9,322" },
];

// =====================invoices=========================
export const invoices = [
{
id: 1,
invoiceNo: "INV-1001",
customerName: "Rahul Sharma",
phone: "9876543210",
date: "24-06-2026",
},
{
id: 2,
invoiceNo: "INV-1002",
customerName: "Priya Verma",
phone: "9123456780",
date: "23-06-2026",
},
{
id: 3,
invoiceNo: "INV-1003",
customerName: "Amit Singh",
phone: "9988776655",
date: "22-06-2026",
},
{
id: 4,
invoiceNo: "INV-1004",
customerName: "Neha Gupta",
phone: "9871234567",
date: "21-06-2026",
},
{
id: 5,
invoiceNo: "INV-1005",
customerName: "Vikash Kumar",
phone: "9012345678",
date: "20-06-2026",
},
];

